theme: jekyll-theme-cayman
title: Ryan Overton
description: Avid software developer and part-time Code-Merc

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: ryan.overton@outlook.com
  facebook:
  flickr:
  github: onyxprime
  instagram:
  linkedin: rpoverton
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: ryano9791
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/